### PR TITLE
Fix `factory.js` not being published to npm

### PR DESCRIPTION
**Pull request by dasilvacontin**
Fixes `Cannot find module './factory'`.

So nobody is actually using the module or...? 😅

### CODE REVIEW

**Comment by sindresorhus** [comment]
> So nobody is actually using the module or...?

I really hope not.

**Comment by dasilvacontin** [comment]
@sindresorhus so if you have a multiple-file project, you prefer to declare a new `noop` function per file rather than importing a file that declares it once?

Or is it because you never intended anyone to use this?

**Comment by sindresorhus** [comment]
I just do `() => {}` inline (noop arrow function).

**Comment by dasilvacontin** [comment]
Yeah, I guess it doesn't really help readability, to use a var named `noop`...

Thanks for sharing!

**Pull request merged**
